const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../dist/core.js'),I=require('../dist/import-core.js'),K=require('../dist/clean-core.js'),L=require('../dist/i18n.js'),X=require('../dist/vendor/xlsx.full.min.js');
const ja=require('../dist/locales/ja.js'),en=require('../dist/locales/en.js');
function table(raw){const detection=C.detectHeader(raw);return {...C.table(raw.slice(detection.headerRow-1),detection.hasHeader),sourceHeaderRow:detection.headerRow,sourceHasHeader:detection.hasHeader};}
test('Clean reuses detected header; keeps interior blanks and original data immutable',()=>{const raw=[['Report'],[],['Product','Lot','Value'],['A','00123',3],[],['B','9007199254740993',4],[]],before=structuredClone(raw),d=table(raw),p=K.prepare(d);assert.equal(d.sourceHeaderRow,3);assert.equal(p.rows.length,3);assert.equal(p.rows[0][1],'00123');assert.equal(p.rows[2][1],'9007199254740993');p.headers[0]='Changed';p.rows[0][0]='Changed';assert.deepEqual(raw,before);assert.equal(d.rows[0][0],'A');});
test('Clean default values preserve outliers, missing data, errors and nonnumeric markers',()=>{const rows=[['0001','ND',-900],['0002','',900000],['0003','#DIV/0!',null]];assert.deepEqual(K.prepare({headers:['ID','Value','Other'],rows}).rows,rows.map(r=>r.map(v=>v??'')));});
test('Explicit types never impute failed values; unsafe numeric conversion is blocked',()=>{const d={headers:['ID','Value'],rows:[['9007199254740993','ND'],['0007','12.5'],['','']]},p=K.prepare(d,[{name:'ID',type:'number'},{name:'Value',type:'number'}]);assert.equal(p.issues.length,2);assert.equal(p.rows[0][0],'9007199254740993');assert.equal(p.rows[0][1],'ND');assert.deepEqual(p.rows[1],[7,12.5]);assert.deepEqual(p.rows[2],['','']);assert.deepEqual(d.rows[1],['0007','12.5']);});
test('Names are editable, unique and nonblank',()=>{const d={headers:['A','B'],rows:[[1,2]]};assert.equal(K.prepare(d,[{name:'Renamed'}]).headers[0],'Renamed');assert.equal(K.prepare(d,[{name:'A'},{name:' A '}]).issues[0].code,'duplicateHeader');assert.equal(K.prepare(d,[{name:''}]).issues[0].code,'emptyHeader');});
for(const date1904 of [false,true])test(`XLSX roundtrip preserves dates, styles and text IDs (${date1904?'1904':'1900'})`,()=>{const source=X.utils.aoa_to_sheet([['Report'],[],['Date','Lot','Value'],[40000.5,'00123',12.3]]);source.A4.z='yyyy-mm-dd hh:mm:ss';const d={...table(I.sheetRows(X,source)),date1904},p=K.prepare(d,[],{sourceSheet:source,X});const wb=K.workbook(X,p),out=X.read(X.write(wb,{type:'buffer',bookType:'xlsx'}),{type:'buffer',cellNF:true});assert.equal(out.Workbook.WBProps.date1904,date1904);assert.equal(out.Sheets.Cleaned.A2.v,40000.5);assert.equal(out.Sheets.Cleaned.A2.z,'yyyy-mm-dd hh:mm:ss');assert.equal(out.Sheets.Cleaned.B2.v,'00123');assert.equal(out.Sheets.Cleaned.B2.t,'s');assert.deepEqual(I.date(out.Sheets.Cleaned.A2.v,date1904),I.date(40000.5,date1904));const csv=K.prepare(d,[],{format:'csv',sourceSheet:source,X});assert.equal(csv.rows[0][0],date1904?'2013-07-07T12:00:00':'2009-07-06T12:00:00');assert.equal(csv.changes.csvDates,1);});
test('Cached formula values and Excel errors are explicit; missing results block even trimmed rows',()=>{const sheet=X.utils.aoa_to_sheet([['A','B'],[3,1]]);sheet.A2.f='1+2';sheet.B2={t:'e',v:7,w:'#DIV/0!'};sheet.A3={t:'n',f:'1+2'};sheet['!ref']='A1:B3';const d={...C.table(I.sheetRows(X,sheet),true),sourceHeaderRow:1,sourceHasHeader:true},p=K.prepare(d,[],{X,sourceSheet:sheet});assert.equal(p.rows[0][0],3);assert.equal(p.rows[0][1],'#DIV/0!');assert.equal(p.changes.formulaValues,1);assert.equal(p.issues[0].code,'formulaMissing');const out=K.workbook(X,p);assert.equal(out.Sheets.Cleaned.A2.f,undefined);assert.equal(out.Sheets.Cleaned.B2.t,'s');});
test('CSV quotes every field, supports BOM/multiline, preserves formula-like text and IDs',()=>{const d={headers:['Name','Value'],rows:[['="x"','00123'],['a,b','line1\nline2'],['平均','未確認']]};const p=K.prepare(d),csv=K.csv(p);assert.ok(csv.startsWith('\uFEFF'));assert.deepEqual(C.csv(csv,','),[d.headers,...d.rows]);assert.equal(p.formulaLike,1);const wb=K.workbook(X,p);assert.equal(wb.Sheets.Cleaned.A2.t,'s');assert.equal(wb.Sheets.Cleaned.A2.f,undefined);});
test('Date conversion is explicit and rejects nonexistent dates without substituting',()=>{const d={headers:['Date'],rows:[['2026-02-30'],['2026-09-30T10:00:00+09:00'],['2026-09-30']]};const p=K.prepare(d,[{type:'date'}]);assert.equal(p.issues[0].code,'invalidDate');assert.equal(p.rows[0][0],'2026-02-30');assert.equal(p.rows[1][0],'2026-09-30T01:00:00Z');assert.equal(p.rows[2][0],'2026-09-30T00:00:00');});
test('Export filenames and shared feature flag have no plan dependency',()=>{assert.equal(K.filename('original.report.xlsx','csv'),'original.report_cleaned.csv');assert.equal(K.canUse('cleanExport'),true);assert.equal(K.canUse('cleanExport',{cleanExport:false}),false);assert.equal(K.canUse('other'),false);});
test('JA/EN catalogs have identical keys/placeholders and English has no Japanese UI text',()=>{assert.deepEqual(Object.keys(ja).sort(),Object.keys(en).sort());for(const key of Object.keys(ja)){assert.deepEqual([...ja[key].matchAll(/\{\d+\}/g)].map(x=>x[0]).sort(),[...en[key].matchAll(/\{\d+\}/g)].map(x=>x[0]).sort(),key);assert.doesNotMatch(en[key],/[\u3040-\u30ff\u3400-\u9fff]/u,key);}});
test('All literal UI translation keys exist; shared language changes do not modify data',()=>{for(const file of fs.readdirSync(path.join(__dirname,'../dist')).filter(f=>f.endsWith('.js'))){const s=fs.readFileSync(path.join(__dirname,'../dist',file),'utf8');for(const m of s.matchAll(/I18n\.t\(['"]([^'"]+)['"]\s*[,)]/g))assert.ok(ja[m[1]],file+': '+m[1]);}const d={headers:['平均','未確認'],rows:[['単一工程','00123']]},before=structuredClone(d);L.setLanguage('en');assert.equal(L.t('clean.title'),'Clean & Export');assert.deepEqual(K.prepare(d).headers,d.headers);assert.deepEqual(d,before);L.setLanguage('ja');});
test('Statistical math and stable generated column names are language independent',()=>{const values=[1,2,3,4,5],r=C.analyze(values,0,6);L.setLanguage('en');assert.deepEqual(C.analyze(values,0,6),r);assert.deepEqual(C.table([['',1],[2,3]],true).headers,['列 1','1']);assert.throws(()=>C.analyze(values,6,0),/lower|LSL/i);L.setLanguage('ja');});

test('ISO wall milliseconds, numeric underflow and CSV formula headers are protected',()=>{assert.equal(K.prepare({headers:['Date'],rows:[['2026-09-30 10:00:00.123']]},[{type:'date'}]).rows[0][0],'2026-09-30T10:00:00.123');assert.equal(K.prepare({headers:['Value'],rows:[['1e-324']]},[{type:'number'}]).issues[0].code,'precision');assert.equal(K.prepare({headers:['=1+1'],rows:[[3]]}).formulaLike,1);});
