const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../dist/core.js'),S=require('../dist/spc-core.js'),Y=require('../dist/cycle-core.js'),R=require('./reference/statistical-reference.json');
const near=(a,b,label='')=>{if(b===null)return assert.equal(a,null,label);assert.ok(Number.isFinite(a)&&Math.abs(a-b)<=1e-10*Math.max(1,Math.abs(b)),`${label}: ${a} != ${b}`);};
for(const f of R.individuals)test('独立Decimal / XmR: '+f.name,()=>{const r=S.analyze(f.raw,{lsl:f.lsl,usl:f.usl});for(const k of ['n','excluded','mean','sd','mr','within','cp','cpk','pp','ppk','lcl','ucl'])near(r[k],f.expected[k],k);r.rangeRecords.forEach((v,i)=>near(v.value,f.expected.movingRanges[i]));near(r.rangeLcl,f.expected.mrLcl);near(r.rangeUcl,f.expected.mrUclDerived);assert.deepEqual(r.oos.map(x=>x.index),f.expected.oosIndices);});
for(const f of R.xbarR)test('独立Decimal / Xbar-R: '+f.name,()=>{const r=S.analyze(f.groups.flat(),{chart:'xbar',subgroupSize:f.subgroupSize,lsl:f.lsl,usl:f.usl});for(const k of ['mean','sd','within','rangeMean','rangeLcl','rangeUcl','cp','cpk','pp','ppk'])near(r[k],f.expected[k],k);near(r.lcl,f.expected.xbarLcl);near(r.ucl,f.expected.xbarUcl);r.groups.forEach((g,i)=>{near(g.mean,f.expected.groupMeans[i]);near(g.range,f.expected.groupRanges[i]);});for(const k of ['d2','d3','A2','D3','D4'])near(r.constants[k],f.constants[k]);});
const allRules=[1,2,3,4,5,6,7,8],hits=v=>S.nelson(v.map((value,index)=>({value,index})),0,1,allRules).map(({rule,index,startIndex})=>({rule,index,startIndex}));
for(const f of R.nelsonTargetVectors){test(`Nelson ${f.rule}: 独立参照の陽性と終点`,()=>{assert.deepEqual(hits(f.values),f.expectedAllSignals);assert.ok(hits(f.values).some(h=>h.rule===f.rule&&h.index===f.triggerIndex));});test(`Nelson ${f.rule}: 陰性`,()=>assert.deepEqual(hits(f.negative),f.negativeExpectedAllSignals));}
for(const f of R.nelsonBoundaryFixtures)test('Nelson境界: '+f.name,()=>assert.deepEqual(hits(f.values),f.expected));
test('元indexの断絶とσ=0では連続ルールが成立しない',()=>{assert.deepEqual(S.nelson(Array.from({length:9},(_,i)=>({index:i+(i>=5?1:0),value:1})),0,1,[2]),[]);assert.deepEqual(S.nelson([{value:100,index:0}],0,0,allRules),[]);assert.throws(()=>S.nelson([],0,1,['1']));assert.throws(()=>S.nelson([],0,1,[9]));});
test('Xbar-Rの欠測群・不完全群は元の群ごと除外',()=>{const r=S.analyze([1,2,3,'',5,6,7],{chart:'xbar',subgroupSize:2,lsl:0,usl:8});assert.equal(r.n,4);assert.equal(r.excluded,3);assert.deepEqual(r.chartRecords.map(x=>x.index),[0,2]);assert.deepEqual(r.excludedGroups.map(x=>x.index),[1,3]);near(r.mean,3.5);near(r.rangeMean,1);assert.equal(r.alarms.filter(x=>x.rule===3).length,0);});
test('Xbar-Rの最小群数と群サイズ・型',()=>{assert.throws(()=>S.analyze([1,2,3],{chart:'xbar',subgroupSize:2}));for(const subgroupSize of [1,11,2.5,'2'])assert.throws(()=>S.analyze([1,2,3,4],{chart:'xbar',subgroupSize}));assert.throws(()=>S.analyze([1,2,3],{chart:'p'}));});
test('全体sと工程内σを混同しない・片側と定数群',()=>{const r=S.analyze([1,2,10,11,20,21],{chart:'xbar',subgroupSize:2,usl:30});assert.equal(r.cp,null);near(r.within,1/1.128);assert.ok(r.sd>r.within*5);near(r.cpk,(30-r.mean)/(3*r.within));const z=S.analyze([1,1,2,2],{chart:'xbar',subgroupSize:2,lsl:0,usl:3});assert.equal(z.cpk,null);assert.ok(z.ppk>0);});
test('過大数値はNaN/Infinityの結果を表示しない',()=>{assert.throws(()=>C.pareto([['A',1e308],['A',1e308]]));assert.throws(()=>C.analyze([1,2,3],-1e308,1e308));assert.throws(()=>S.analyze([1e-310,2e-310],{lsl:0,usl:1e100}));const p=C.pareto([['A',1e307],['B',1e307]]);near(p.items[1].cumulative,100);});
test('パレートは独立集計の比率・累積比率と一致',()=>assert.deepEqual(C.pareto(R.pareto.raw),R.pareto.expected));
for(const [i,f] of R.quantiles.entries())test('R7 / Excel PERCENTILE.INC互換: '+i,()=>{near(Y.percentile(f.values,.25),f.p25);near(Y.percentile(f.values,.5),f.p50);});
test('分位点の端点・空配列・不正値',()=>{assert.equal(Y.percentile([],0),null);assert.equal(Y.percentile([5,10],0),5);assert.equal(Y.percentile([5,10],1),10);for(const p of [-1,1.1,NaN,'0.5'])assert.throws(()=>Y.percentile([1,2],p));assert.throws(()=>Y.percentile([NaN],.5));});
test('Cycle Timeは独立datetime計算と一致・異製品を飛ばさない',()=>{const f=R.cycle,r=Y.analyze(f.rows,f.columns,{minSamples:2}),e=f.expected;for(const [key,name] of [['processing','processingMinutesByInputIndex'],['gap','gapMinutesByInputIndex'],['cycle','cycleMinutesByInputIndex']])r.records.forEach((v,i)=>near(v[key],e[name][i]));const a=r.groups.find(g=>g.product==='A');assert.equal(a.cycle.n,e.productACycleN);near(a.cycle.p25,e.productACycleP25);near(a.cycle.p50,e.productACycleP50);});
test('1904方式の0と1900方式の架空うるう日は区別',()=>{assert.equal(Y.timestamp(0,true).ms,Date.UTC(1904,0,1));assert.equal(Y.timestamp(0,false),null);assert.equal(Y.timestamp(60,false),null);});
